[package]
name = "erosion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.10"
env_logger = "0.11"
log = "0.4"
wgpu = "0.19.0"
pollster = "0.3.0"

[lib]
crate-type = ["rlib"]